name: 自动发布正式版
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    # 👇 关键：仅当标签属于 main 分支时发布
    if: github.event.base_ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: 发布Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          generate_release_notes: true
          files: "**/*menu*.catvba"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}